// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace guiprotocol {

namespace {

const ::google::protobuf::EnumDescriptor* GameState_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* Player_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2eproto() {
  protobuf_AddDesc_common_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common.proto");
  GOOGLE_CHECK(file != NULL);
  GameState_descriptor_ = file->enum_type(0);
  Player_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_common_2eproto() {
}

void protobuf_AddDesc_common_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014common.proto\022\013guiprotocol*\346\001\n\tGameStat"
    "e\022\014\n\010NO_STATE\020\000\022\031\n\025ROUND_BEGINNING_STATE"
    "\020\001\022\027\n\023ROUND_IN_PLAY_STATE\020\002\022\025\n\021ROUND_END"
    "ED_STATE\020\003\022\033\n\027TIE_BREAKER_ROUND_STATE\020\004\022"
    "\025\n\021MATCH_ENDED_STATE\020\005\022\020\n\014PAUSED_STATE\020\006"
    "\022\024\n\020RINGMASTER_STATE\020\007\022\016\n\nIDLE_STATE\020\010\022\024"
    "\n\020TEST_ROUND_STATE\020\t*(\n\006Player\022\016\n\nRINGMA"
    "STER\020\000\022\006\n\002P1\020\001\022\006\n\002P2\020\002B\032\n\030ca.site3.ssf.g"
    "uiprotocol", 330);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2eproto {
  StaticDescriptorInitializer_common_2eproto() {
    protobuf_AddDesc_common_2eproto();
  }
} static_descriptor_initializer_common_2eproto_;

const ::google::protobuf::EnumDescriptor* GameState_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GameState_descriptor_;
}
bool GameState_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Player_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Player_descriptor_;
}
bool Player_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guiprotocol

// @@protoc_insertion_point(global_scope)
