// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package ca.site3.ssf.guiprotocol;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GameState
      implements com.google.protobuf.ProtocolMessageEnum {
    NO_STATE(0, 0),
    ROUND_BEGINNING_STATE(1, 1),
    ROUND_IN_PLAY_STATE(2, 2),
    ROUND_ENDED_STATE(3, 3),
    TIE_BREAKER_ROUND_STATE(4, 4),
    MATCH_ENDED_STATE(5, 5),
    PAUSED_STATE(6, 6),
    RINGMASTER_STATE(7, 7),
    IDLE_STATE(8, 8),
    TEST_ROUND_STATE(9, 9),
    ;
    
    public static final int NO_STATE_VALUE = 0;
    public static final int ROUND_BEGINNING_STATE_VALUE = 1;
    public static final int ROUND_IN_PLAY_STATE_VALUE = 2;
    public static final int ROUND_ENDED_STATE_VALUE = 3;
    public static final int TIE_BREAKER_ROUND_STATE_VALUE = 4;
    public static final int MATCH_ENDED_STATE_VALUE = 5;
    public static final int PAUSED_STATE_VALUE = 6;
    public static final int RINGMASTER_STATE_VALUE = 7;
    public static final int IDLE_STATE_VALUE = 8;
    public static final int TEST_ROUND_STATE_VALUE = 9;
    
    
    public final int getNumber() { return value; }
    
    public static GameState valueOf(int value) {
      switch (value) {
        case 0: return NO_STATE;
        case 1: return ROUND_BEGINNING_STATE;
        case 2: return ROUND_IN_PLAY_STATE;
        case 3: return ROUND_ENDED_STATE;
        case 4: return TIE_BREAKER_ROUND_STATE;
        case 5: return MATCH_ENDED_STATE;
        case 6: return PAUSED_STATE;
        case 7: return RINGMASTER_STATE;
        case 8: return IDLE_STATE;
        case 9: return TEST_ROUND_STATE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameState>() {
            public GameState findValueByNumber(int number) {
              return GameState.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ca.site3.ssf.guiprotocol.Common.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GameState[] VALUES = {
      NO_STATE, ROUND_BEGINNING_STATE, ROUND_IN_PLAY_STATE, ROUND_ENDED_STATE, TIE_BREAKER_ROUND_STATE, MATCH_ENDED_STATE, PAUSED_STATE, RINGMASTER_STATE, IDLE_STATE, TEST_ROUND_STATE, 
    };
    
    public static GameState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GameState(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:guiprotocol.GameState)
  }
  
  public enum Player
      implements com.google.protobuf.ProtocolMessageEnum {
    RINGMASTER(0, 0),
    P1(1, 1),
    P2(2, 2),
    ;
    
    public static final int RINGMASTER_VALUE = 0;
    public static final int P1_VALUE = 1;
    public static final int P2_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static Player valueOf(int value) {
      switch (value) {
        case 0: return RINGMASTER;
        case 1: return P1;
        case 2: return P2;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Player>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Player>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Player>() {
            public Player findValueByNumber(int number) {
              return Player.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ca.site3.ssf.guiprotocol.Common.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Player[] VALUES = {
      RINGMASTER, P1, P2, 
    };
    
    public static Player valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Player(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:guiprotocol.Player)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\013guiprotocol*\346\001\n\tGameStat" +
      "e\022\014\n\010NO_STATE\020\000\022\031\n\025ROUND_BEGINNING_STATE" +
      "\020\001\022\027\n\023ROUND_IN_PLAY_STATE\020\002\022\025\n\021ROUND_END" +
      "ED_STATE\020\003\022\033\n\027TIE_BREAKER_ROUND_STATE\020\004\022" +
      "\025\n\021MATCH_ENDED_STATE\020\005\022\020\n\014PAUSED_STATE\020\006" +
      "\022\024\n\020RINGMASTER_STATE\020\007\022\016\n\nIDLE_STATE\020\010\022\024" +
      "\n\020TEST_ROUND_STATE\020\t*(\n\006Player\022\016\n\nRINGMA" +
      "STER\020\000\022\006\n\002P1\020\001\022\006\n\002P2\020\002B\032\n\030ca.site3.ssf.g" +
      "uiprotocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
