// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/discovery.proto

package ca.site3.ssf.guiprotocol;

public final class Discovery {
  private Discovery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DiscoveryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string appName = 2;
    boolean hasAppName();
    String getAppName();
    
    // optional .guiprotocol.DiscoveryRequest.DiscoveryAppType appType = 3;
    boolean hasAppType();
    ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType getAppType();
  }
  public static final class DiscoveryRequest extends
      com.google.protobuf.GeneratedMessage
      implements DiscoveryRequestOrBuilder {
    // Use DiscoveryRequest.newBuilder() to construct.
    private DiscoveryRequest(Builder builder) {
      super(builder);
    }
    private DiscoveryRequest(boolean noInit) {}
    
    private static final DiscoveryRequest defaultInstance;
    public static DiscoveryRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DiscoveryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryRequest_fieldAccessorTable;
    }
    
    public enum DiscoveryAppType
        implements com.google.protobuf.ProtocolMessageEnum {
      GUI(0, 0),
      ;
      
      public static final int GUI_VALUE = 0;
      
      
      public final int getNumber() { return value; }
      
      public static DiscoveryAppType valueOf(int value) {
        switch (value) {
          case 0: return GUI;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DiscoveryAppType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DiscoveryAppType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DiscoveryAppType>() {
              public DiscoveryAppType findValueByNumber(int number) {
                return DiscoveryAppType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final DiscoveryAppType[] VALUES = {
        GUI, 
      };
      
      public static DiscoveryAppType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DiscoveryAppType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.DiscoveryRequest.DiscoveryAppType)
    }
    
    private int bitField0_;
    // optional string appName = 2;
    public static final int APPNAME_FIELD_NUMBER = 2;
    private java.lang.Object appName_;
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          appName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .guiprotocol.DiscoveryRequest.DiscoveryAppType appType = 3;
    public static final int APPTYPE_FIELD_NUMBER = 3;
    private ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType appType_;
    public boolean hasAppType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType getAppType() {
      return appType_;
    }
    
    private void initFields() {
      appName_ = "";
      appType_ = ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType.GUI;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, appType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, appType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryRequest_fieldAccessorTable;
      }
      
      // Construct using ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        appType_ = ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType.GUI;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.getDescriptor();
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest getDefaultInstanceForType() {
        return ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.getDefaultInstance();
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest build() {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest buildPartial() {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest result = new ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appType_ = appType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest) {
          return mergeFrom((ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest other) {
        if (other == ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.getDefaultInstance()) return this;
        if (other.hasAppName()) {
          setAppName(other.getAppName());
        }
        if (other.hasAppType()) {
          setAppType(other.getAppType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              appName_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType value = ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                appType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string appName = 2;
      private java.lang.Object appName_ = "";
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAppName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      void setAppName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        appName_ = value;
        onChanged();
      }
      
      // optional .guiprotocol.DiscoveryRequest.DiscoveryAppType appType = 3;
      private ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType appType_ = ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType.GUI;
      public boolean hasAppType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType getAppType() {
        return appType_;
      }
      public Builder setAppType(ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        appType_ = value;
        onChanged();
        return this;
      }
      public Builder clearAppType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appType_ = ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.DiscoveryAppType.GUI;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:guiprotocol.DiscoveryRequest)
    }
    
    static {
      defaultInstance = new DiscoveryRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:guiprotocol.DiscoveryRequest)
  }
  
  public interface DiscoveryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string serverIPAddress = 1;
    boolean hasServerIPAddress();
    String getServerIPAddress();
    
    // required int32 serverPortNumber = 2;
    boolean hasServerPortNumber();
    int getServerPortNumber();
  }
  public static final class DiscoveryResponse extends
      com.google.protobuf.GeneratedMessage
      implements DiscoveryResponseOrBuilder {
    // Use DiscoveryResponse.newBuilder() to construct.
    private DiscoveryResponse(Builder builder) {
      super(builder);
    }
    private DiscoveryResponse(boolean noInit) {}
    
    private static final DiscoveryResponse defaultInstance;
    public static DiscoveryResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DiscoveryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string serverIPAddress = 1;
    public static final int SERVERIPADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object serverIPAddress_;
    public boolean hasServerIPAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getServerIPAddress() {
      java.lang.Object ref = serverIPAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serverIPAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServerIPAddressBytes() {
      java.lang.Object ref = serverIPAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serverIPAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 serverPortNumber = 2;
    public static final int SERVERPORTNUMBER_FIELD_NUMBER = 2;
    private int serverPortNumber_;
    public boolean hasServerPortNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getServerPortNumber() {
      return serverPortNumber_;
    }
    
    private void initFields() {
      serverIPAddress_ = "";
      serverPortNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasServerIPAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerPortNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerIPAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverPortNumber_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerIPAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverPortNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.site3.ssf.guiprotocol.Discovery.internal_static_guiprotocol_DiscoveryResponse_fieldAccessorTable;
      }
      
      // Construct using ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverIPAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverPortNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.getDescriptor();
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse getDefaultInstanceForType() {
        return ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.getDefaultInstance();
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse build() {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse buildPartial() {
        ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse result = new ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverIPAddress_ = serverIPAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverPortNumber_ = serverPortNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse) {
          return mergeFrom((ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse other) {
        if (other == ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.getDefaultInstance()) return this;
        if (other.hasServerIPAddress()) {
          setServerIPAddress(other.getServerIPAddress());
        }
        if (other.hasServerPortNumber()) {
          setServerPortNumber(other.getServerPortNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasServerIPAddress()) {
          
          return false;
        }
        if (!hasServerPortNumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverIPAddress_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverPortNumber_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string serverIPAddress = 1;
      private java.lang.Object serverIPAddress_ = "";
      public boolean hasServerIPAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getServerIPAddress() {
        java.lang.Object ref = serverIPAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serverIPAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServerIPAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverIPAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerIPAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverIPAddress_ = getDefaultInstance().getServerIPAddress();
        onChanged();
        return this;
      }
      void setServerIPAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        serverIPAddress_ = value;
        onChanged();
      }
      
      // required int32 serverPortNumber = 2;
      private int serverPortNumber_ ;
      public boolean hasServerPortNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getServerPortNumber() {
        return serverPortNumber_;
      }
      public Builder setServerPortNumber(int value) {
        bitField0_ |= 0x00000002;
        serverPortNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerPortNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverPortNumber_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:guiprotocol.DiscoveryResponse)
    }
    
    static {
      defaultInstance = new DiscoveryResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:guiprotocol.DiscoveryResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guiprotocol_DiscoveryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guiprotocol_DiscoveryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guiprotocol_DiscoveryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guiprotocol_DiscoveryResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/discovery.proto\022\013guipro" +
      "tocol\"\201\001\n\020DiscoveryRequest\022\017\n\007appName\030\002 " +
      "\001(\t\022?\n\007appType\030\003 \001(\0162..guiprotocol.Disco" +
      "veryRequest.DiscoveryAppType\"\033\n\020Discover" +
      "yAppType\022\007\n\003GUI\020\000\"F\n\021DiscoveryResponse\022\027" +
      "\n\017serverIPAddress\030\001 \002(\t\022\030\n\020serverPortNum" +
      "ber\030\002 \002(\005B\032\n\030ca.site3.ssf.guiprotocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_guiprotocol_DiscoveryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_guiprotocol_DiscoveryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guiprotocol_DiscoveryRequest_descriptor,
              new java.lang.String[] { "AppName", "AppType", },
              ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.class,
              ca.site3.ssf.guiprotocol.Discovery.DiscoveryRequest.Builder.class);
          internal_static_guiprotocol_DiscoveryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_guiprotocol_DiscoveryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guiprotocol_DiscoveryResponse_descriptor,
              new java.lang.String[] { "ServerIPAddress", "ServerPortNumber", },
              ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.class,
              ca.site3.ssf.guiprotocol.Discovery.DiscoveryResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
