// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package ca.site3.ssf.guiprotocol;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .guiprotocol.GameEvent.EventType type = 1;
    boolean hasType();
    ca.site3.ssf.guiprotocol.Event.GameEvent.EventType getType();
    
    // optional .guiprotocol.GameEvent.FireEmitter emitter = 2;
    boolean hasEmitter();
    ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter getEmitter();
    ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder getEmitterOrBuilder();
    
    // optional .guiprotocol.GameEvent.GameState oldGameState = 3;
    boolean hasOldGameState();
    ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getOldGameState();
    
    // optional .guiprotocol.GameEvent.GameState newGameState = 4;
    boolean hasNewGameState();
    ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getNewGameState();
    
    // optional .guiprotocol.GameEvent.Player matchWinner = 5;
    boolean hasMatchWinner();
    ca.site3.ssf.guiprotocol.Event.GameEvent.Player getMatchWinner();
    
    // optional .guiprotocol.GameEvent.Player player = 6;
    boolean hasPlayer();
    ca.site3.ssf.guiprotocol.Event.GameEvent.Player getPlayer();
    
    // optional .guiprotocol.GameEvent.AttackType attackType = 7;
    boolean hasAttackType();
    ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType getAttackType();
    
    // optional float oldHealth = 9;
    boolean hasOldHealth();
    float getOldHealth();
    
    // optional float newHealth = 10;
    boolean hasNewHealth();
    float getNewHealth();
    
    // optional int32 roundNumber = 11;
    boolean hasRoundNumber();
    int getRoundNumber();
    
    // optional int32 beginType = 12;
    boolean hasBeginType();
    int getBeginType();
    
    // optional .guiprotocol.GameEvent.Player roundWinner = 13;
    boolean hasRoundWinner();
    ca.site3.ssf.guiprotocol.Event.GameEvent.Player getRoundWinner();
    
    // optional bool timedOut = 14;
    boolean hasTimedOut();
    boolean getTimedOut();
    
    // optional int32 timeInSecs = 15;
    boolean hasTimeInSecs();
    int getTimeInSecs();
  }
  public static final class GameEvent extends
      com.google.protobuf.GeneratedMessage
      implements GameEventOrBuilder {
    // Use GameEvent.newBuilder() to construct.
    private GameEvent(Builder builder) {
      super(builder);
    }
    private GameEvent(boolean noInit) {}
    
    private static final GameEvent defaultInstance;
    public static GameEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_fieldAccessorTable;
    }
    
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      FireEmitterChanged(0, 0),
      GameStateChanged(1, 1),
      PlayerHealthChanged(2, 2),
      RoundPlayTimerChanged(3, 3),
      RoundBeginTimerChanged(4, 4),
      RoundEnded(5, 5),
      MatchEnded(6, 6),
      PlayerAttackAction(7, 7),
      PlayerBlockAction(8, 8),
      RingmasterAction(9, 9),
      ;
      
      public static final int FireEmitterChanged_VALUE = 0;
      public static final int GameStateChanged_VALUE = 1;
      public static final int PlayerHealthChanged_VALUE = 2;
      public static final int RoundPlayTimerChanged_VALUE = 3;
      public static final int RoundBeginTimerChanged_VALUE = 4;
      public static final int RoundEnded_VALUE = 5;
      public static final int MatchEnded_VALUE = 6;
      public static final int PlayerAttackAction_VALUE = 7;
      public static final int PlayerBlockAction_VALUE = 8;
      public static final int RingmasterAction_VALUE = 9;
      
      
      public final int getNumber() { return value; }
      
      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return FireEmitterChanged;
          case 1: return GameStateChanged;
          case 2: return PlayerHealthChanged;
          case 3: return RoundPlayTimerChanged;
          case 4: return RoundBeginTimerChanged;
          case 5: return RoundEnded;
          case 6: return MatchEnded;
          case 7: return PlayerAttackAction;
          case 8: return PlayerBlockAction;
          case 9: return RingmasterAction;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EventType[] VALUES = {
        FireEmitterChanged, GameStateChanged, PlayerHealthChanged, RoundPlayTimerChanged, RoundBeginTimerChanged, RoundEnded, MatchEnded, PlayerAttackAction, PlayerBlockAction, RingmasterAction, 
      };
      
      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.EventType)
    }
    
    public enum GameState
        implements com.google.protobuf.ProtocolMessageEnum {
      NO_STATE(0, 0),
      ROUND_BEGINNING_STATE(1, 1),
      ROUND_IN_PLAY_STATE(2, 2),
      ROUND_ENDED_STATE(3, 3),
      TIE_BREAKER_ROUND_STATE(4, 4),
      MATCH_ENDED_STATE(5, 5),
      PAUSED_STATE(6, 6),
      RINGMASTER_STATE(7, 7),
      IDLE_STATE(8, 8),
      ;
      
      public static final int NO_STATE_VALUE = 0;
      public static final int ROUND_BEGINNING_STATE_VALUE = 1;
      public static final int ROUND_IN_PLAY_STATE_VALUE = 2;
      public static final int ROUND_ENDED_STATE_VALUE = 3;
      public static final int TIE_BREAKER_ROUND_STATE_VALUE = 4;
      public static final int MATCH_ENDED_STATE_VALUE = 5;
      public static final int PAUSED_STATE_VALUE = 6;
      public static final int RINGMASTER_STATE_VALUE = 7;
      public static final int IDLE_STATE_VALUE = 8;
      
      
      public final int getNumber() { return value; }
      
      public static GameState valueOf(int value) {
        switch (value) {
          case 0: return NO_STATE;
          case 1: return ROUND_BEGINNING_STATE;
          case 2: return ROUND_IN_PLAY_STATE;
          case 3: return ROUND_ENDED_STATE;
          case 4: return TIE_BREAKER_ROUND_STATE;
          case 5: return MATCH_ENDED_STATE;
          case 6: return PAUSED_STATE;
          case 7: return RINGMASTER_STATE;
          case 8: return IDLE_STATE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<GameState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<GameState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GameState>() {
              public GameState findValueByNumber(int number) {
                return GameState.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final GameState[] VALUES = {
        NO_STATE, ROUND_BEGINNING_STATE, ROUND_IN_PLAY_STATE, ROUND_ENDED_STATE, TIE_BREAKER_ROUND_STATE, MATCH_ENDED_STATE, PAUSED_STATE, RINGMASTER_STATE, IDLE_STATE, 
      };
      
      public static GameState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private GameState(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.GameState)
    }
    
    public enum Player
        implements com.google.protobuf.ProtocolMessageEnum {
      RINGMASTER(0, 0),
      P1(1, 1),
      P2(2, 2),
      ;
      
      public static final int RINGMASTER_VALUE = 0;
      public static final int P1_VALUE = 1;
      public static final int P2_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Player valueOf(int value) {
        switch (value) {
          case 0: return RINGMASTER;
          case 1: return P1;
          case 2: return P2;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Player>() {
              public Player findValueByNumber(int number) {
                return Player.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(2);
      }
      
      private static final Player[] VALUES = {
        RINGMASTER, P1, P2, 
      };
      
      public static Player valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Player(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.Player)
    }
    
    public enum FireEmitterType
        implements com.google.protobuf.ProtocolMessageEnum {
      LEFT_RAIL(0, 0),
      RIGHT_RAIL(1, 1),
      OUTER_RING(2, 2),
      ;
      
      public static final int LEFT_RAIL_VALUE = 0;
      public static final int RIGHT_RAIL_VALUE = 1;
      public static final int OUTER_RING_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static FireEmitterType valueOf(int value) {
        switch (value) {
          case 0: return LEFT_RAIL;
          case 1: return RIGHT_RAIL;
          case 2: return OUTER_RING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<FireEmitterType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FireEmitterType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FireEmitterType>() {
              public FireEmitterType findValueByNumber(int number) {
                return FireEmitterType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(3);
      }
      
      private static final FireEmitterType[] VALUES = {
        LEFT_RAIL, RIGHT_RAIL, OUTER_RING, 
      };
      
      public static FireEmitterType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private FireEmitterType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.FireEmitterType)
    }
    
    public enum FlameEmitterType
        implements com.google.protobuf.ProtocolMessageEnum {
      ATTACK_FLAME(0, 0),
      BLOCK_FLAME(1, 1),
      NON_GAME_FLAME(2, 2),
      ;
      
      public static final int ATTACK_FLAME_VALUE = 0;
      public static final int BLOCK_FLAME_VALUE = 1;
      public static final int NON_GAME_FLAME_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static FlameEmitterType valueOf(int value) {
        switch (value) {
          case 0: return ATTACK_FLAME;
          case 1: return BLOCK_FLAME;
          case 2: return NON_GAME_FLAME;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<FlameEmitterType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FlameEmitterType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FlameEmitterType>() {
              public FlameEmitterType findValueByNumber(int number) {
                return FlameEmitterType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(4);
      }
      
      private static final FlameEmitterType[] VALUES = {
        ATTACK_FLAME, BLOCK_FLAME, NON_GAME_FLAME, 
      };
      
      public static FlameEmitterType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private FlameEmitterType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.FlameEmitterType)
    }
    
    public enum AttackType
        implements com.google.protobuf.ProtocolMessageEnum {
      LEFT_JAB(0, 0),
      RIGHT_JAB(1, 1),
      LEFT_HOOK(2, 2),
      RIGHT_HOOK(3, 3),
      HADOUKEN(4, 4),
      SONIC_BOOM(5, 5),
      ;
      
      public static final int LEFT_JAB_VALUE = 0;
      public static final int RIGHT_JAB_VALUE = 1;
      public static final int LEFT_HOOK_VALUE = 2;
      public static final int RIGHT_HOOK_VALUE = 3;
      public static final int HADOUKEN_VALUE = 4;
      public static final int SONIC_BOOM_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static AttackType valueOf(int value) {
        switch (value) {
          case 0: return LEFT_JAB;
          case 1: return RIGHT_JAB;
          case 2: return LEFT_HOOK;
          case 3: return RIGHT_HOOK;
          case 4: return HADOUKEN;
          case 5: return SONIC_BOOM;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<AttackType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AttackType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AttackType>() {
              public AttackType findValueByNumber(int number) {
                return AttackType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor().getEnumTypes().get(5);
      }
      
      private static final AttackType[] VALUES = {
        LEFT_JAB, RIGHT_JAB, LEFT_HOOK, RIGHT_HOOK, HADOUKEN, SONIC_BOOM, 
      };
      
      public static AttackType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private AttackType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:guiprotocol.GameEvent.AttackType)
    }
    
    public interface FireEmitterOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 emitterIndex = 1;
      boolean hasEmitterIndex();
      int getEmitterIndex();
      
      // required .guiprotocol.GameEvent.FireEmitterType emitterType = 2;
      boolean hasEmitterType();
      ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType getEmitterType();
      
      // required float intensityRingmaster = 3;
      boolean hasIntensityRingmaster();
      float getIntensityRingmaster();
      
      // required float intensityPlayer1 = 4;
      boolean hasIntensityPlayer1();
      float getIntensityPlayer1();
      
      // required float intensityPlayer2 = 5;
      boolean hasIntensityPlayer2();
      float getIntensityPlayer2();
    }
    public static final class FireEmitter extends
        com.google.protobuf.GeneratedMessage
        implements FireEmitterOrBuilder {
      // Use FireEmitter.newBuilder() to construct.
      private FireEmitter(Builder builder) {
        super(builder);
      }
      private FireEmitter(boolean noInit) {}
      
      private static final FireEmitter defaultInstance;
      public static FireEmitter getDefaultInstance() {
        return defaultInstance;
      }
      
      public FireEmitter getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_FireEmitter_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_FireEmitter_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 emitterIndex = 1;
      public static final int EMITTERINDEX_FIELD_NUMBER = 1;
      private int emitterIndex_;
      public boolean hasEmitterIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getEmitterIndex() {
        return emitterIndex_;
      }
      
      // required .guiprotocol.GameEvent.FireEmitterType emitterType = 2;
      public static final int EMITTERTYPE_FIELD_NUMBER = 2;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType emitterType_;
      public boolean hasEmitterType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType getEmitterType() {
        return emitterType_;
      }
      
      // required float intensityRingmaster = 3;
      public static final int INTENSITYRINGMASTER_FIELD_NUMBER = 3;
      private float intensityRingmaster_;
      public boolean hasIntensityRingmaster() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getIntensityRingmaster() {
        return intensityRingmaster_;
      }
      
      // required float intensityPlayer1 = 4;
      public static final int INTENSITYPLAYER1_FIELD_NUMBER = 4;
      private float intensityPlayer1_;
      public boolean hasIntensityPlayer1() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getIntensityPlayer1() {
        return intensityPlayer1_;
      }
      
      // required float intensityPlayer2 = 5;
      public static final int INTENSITYPLAYER2_FIELD_NUMBER = 5;
      private float intensityPlayer2_;
      public boolean hasIntensityPlayer2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getIntensityPlayer2() {
        return intensityPlayer2_;
      }
      
      private void initFields() {
        emitterIndex_ = 0;
        emitterType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType.LEFT_RAIL;
        intensityRingmaster_ = 0F;
        intensityPlayer1_ = 0F;
        intensityPlayer2_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasEmitterIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEmitterType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIntensityRingmaster()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIntensityPlayer1()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIntensityPlayer2()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, emitterIndex_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, emitterType_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeFloat(3, intensityRingmaster_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(4, intensityPlayer1_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeFloat(5, intensityPlayer2_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, emitterIndex_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, emitterType_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, intensityRingmaster_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, intensityPlayer1_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, intensityPlayer2_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_FireEmitter_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_FireEmitter_fieldAccessorTable;
        }
        
        // Construct using ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          emitterIndex_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          emitterType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType.LEFT_RAIL;
          bitField0_ = (bitField0_ & ~0x00000002);
          intensityRingmaster_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000004);
          intensityPlayer1_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          intensityPlayer2_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDescriptor();
        }
        
        public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter getDefaultInstanceForType() {
          return ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance();
        }
        
        public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter build() {
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter buildPartial() {
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter result = new ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.emitterIndex_ = emitterIndex_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.emitterType_ = emitterType_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.intensityRingmaster_ = intensityRingmaster_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.intensityPlayer1_ = intensityPlayer1_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.intensityPlayer2_ = intensityPlayer2_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter) {
            return mergeFrom((ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter other) {
          if (other == ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance()) return this;
          if (other.hasEmitterIndex()) {
            setEmitterIndex(other.getEmitterIndex());
          }
          if (other.hasEmitterType()) {
            setEmitterType(other.getEmitterType());
          }
          if (other.hasIntensityRingmaster()) {
            setIntensityRingmaster(other.getIntensityRingmaster());
          }
          if (other.hasIntensityPlayer1()) {
            setIntensityPlayer1(other.getIntensityPlayer1());
          }
          if (other.hasIntensityPlayer2()) {
            setIntensityPlayer2(other.getIntensityPlayer2());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasEmitterIndex()) {
            
            return false;
          }
          if (!hasEmitterType()) {
            
            return false;
          }
          if (!hasIntensityRingmaster()) {
            
            return false;
          }
          if (!hasIntensityPlayer1()) {
            
            return false;
          }
          if (!hasIntensityPlayer2()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                emitterIndex_ = input.readInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType value = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  emitterType_ = value;
                }
                break;
              }
              case 29: {
                bitField0_ |= 0x00000004;
                intensityRingmaster_ = input.readFloat();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                intensityPlayer1_ = input.readFloat();
                break;
              }
              case 45: {
                bitField0_ |= 0x00000010;
                intensityPlayer2_ = input.readFloat();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 emitterIndex = 1;
        private int emitterIndex_ ;
        public boolean hasEmitterIndex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getEmitterIndex() {
          return emitterIndex_;
        }
        public Builder setEmitterIndex(int value) {
          bitField0_ |= 0x00000001;
          emitterIndex_ = value;
          onChanged();
          return this;
        }
        public Builder clearEmitterIndex() {
          bitField0_ = (bitField0_ & ~0x00000001);
          emitterIndex_ = 0;
          onChanged();
          return this;
        }
        
        // required .guiprotocol.GameEvent.FireEmitterType emitterType = 2;
        private ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType emitterType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType.LEFT_RAIL;
        public boolean hasEmitterType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType getEmitterType() {
          return emitterType_;
        }
        public Builder setEmitterType(ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          emitterType_ = value;
          onChanged();
          return this;
        }
        public Builder clearEmitterType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          emitterType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterType.LEFT_RAIL;
          onChanged();
          return this;
        }
        
        // required float intensityRingmaster = 3;
        private float intensityRingmaster_ ;
        public boolean hasIntensityRingmaster() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public float getIntensityRingmaster() {
          return intensityRingmaster_;
        }
        public Builder setIntensityRingmaster(float value) {
          bitField0_ |= 0x00000004;
          intensityRingmaster_ = value;
          onChanged();
          return this;
        }
        public Builder clearIntensityRingmaster() {
          bitField0_ = (bitField0_ & ~0x00000004);
          intensityRingmaster_ = 0F;
          onChanged();
          return this;
        }
        
        // required float intensityPlayer1 = 4;
        private float intensityPlayer1_ ;
        public boolean hasIntensityPlayer1() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public float getIntensityPlayer1() {
          return intensityPlayer1_;
        }
        public Builder setIntensityPlayer1(float value) {
          bitField0_ |= 0x00000008;
          intensityPlayer1_ = value;
          onChanged();
          return this;
        }
        public Builder clearIntensityPlayer1() {
          bitField0_ = (bitField0_ & ~0x00000008);
          intensityPlayer1_ = 0F;
          onChanged();
          return this;
        }
        
        // required float intensityPlayer2 = 5;
        private float intensityPlayer2_ ;
        public boolean hasIntensityPlayer2() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        public float getIntensityPlayer2() {
          return intensityPlayer2_;
        }
        public Builder setIntensityPlayer2(float value) {
          bitField0_ |= 0x00000010;
          intensityPlayer2_ = value;
          onChanged();
          return this;
        }
        public Builder clearIntensityPlayer2() {
          bitField0_ = (bitField0_ & ~0x00000010);
          intensityPlayer2_ = 0F;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:guiprotocol.GameEvent.FireEmitter)
      }
      
      static {
        defaultInstance = new FireEmitter(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:guiprotocol.GameEvent.FireEmitter)
    }
    
    private int bitField0_;
    // required .guiprotocol.GameEvent.EventType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.EventType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.EventType getType() {
      return type_;
    }
    
    // optional .guiprotocol.GameEvent.FireEmitter emitter = 2;
    public static final int EMITTER_FIELD_NUMBER = 2;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter emitter_;
    public boolean hasEmitter() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter getEmitter() {
      return emitter_;
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder getEmitterOrBuilder() {
      return emitter_;
    }
    
    // optional .guiprotocol.GameEvent.GameState oldGameState = 3;
    public static final int OLDGAMESTATE_FIELD_NUMBER = 3;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.GameState oldGameState_;
    public boolean hasOldGameState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getOldGameState() {
      return oldGameState_;
    }
    
    // optional .guiprotocol.GameEvent.GameState newGameState = 4;
    public static final int NEWGAMESTATE_FIELD_NUMBER = 4;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.GameState newGameState_;
    public boolean hasNewGameState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getNewGameState() {
      return newGameState_;
    }
    
    // optional .guiprotocol.GameEvent.Player matchWinner = 5;
    public static final int MATCHWINNER_FIELD_NUMBER = 5;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.Player matchWinner_;
    public boolean hasMatchWinner() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getMatchWinner() {
      return matchWinner_;
    }
    
    // optional .guiprotocol.GameEvent.Player player = 6;
    public static final int PLAYER_FIELD_NUMBER = 6;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.Player player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getPlayer() {
      return player_;
    }
    
    // optional .guiprotocol.GameEvent.AttackType attackType = 7;
    public static final int ATTACKTYPE_FIELD_NUMBER = 7;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType attackType_;
    public boolean hasAttackType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType getAttackType() {
      return attackType_;
    }
    
    // optional float oldHealth = 9;
    public static final int OLDHEALTH_FIELD_NUMBER = 9;
    private float oldHealth_;
    public boolean hasOldHealth() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public float getOldHealth() {
      return oldHealth_;
    }
    
    // optional float newHealth = 10;
    public static final int NEWHEALTH_FIELD_NUMBER = 10;
    private float newHealth_;
    public boolean hasNewHealth() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public float getNewHealth() {
      return newHealth_;
    }
    
    // optional int32 roundNumber = 11;
    public static final int ROUNDNUMBER_FIELD_NUMBER = 11;
    private int roundNumber_;
    public boolean hasRoundNumber() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getRoundNumber() {
      return roundNumber_;
    }
    
    // optional int32 beginType = 12;
    public static final int BEGINTYPE_FIELD_NUMBER = 12;
    private int beginType_;
    public boolean hasBeginType() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getBeginType() {
      return beginType_;
    }
    
    // optional .guiprotocol.GameEvent.Player roundWinner = 13;
    public static final int ROUNDWINNER_FIELD_NUMBER = 13;
    private ca.site3.ssf.guiprotocol.Event.GameEvent.Player roundWinner_;
    public boolean hasRoundWinner() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getRoundWinner() {
      return roundWinner_;
    }
    
    // optional bool timedOut = 14;
    public static final int TIMEDOUT_FIELD_NUMBER = 14;
    private boolean timedOut_;
    public boolean hasTimedOut() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public boolean getTimedOut() {
      return timedOut_;
    }
    
    // optional int32 timeInSecs = 15;
    public static final int TIMEINSECS_FIELD_NUMBER = 15;
    private int timeInSecs_;
    public boolean hasTimeInSecs() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getTimeInSecs() {
      return timeInSecs_;
    }
    
    private void initFields() {
      type_ = ca.site3.ssf.guiprotocol.Event.GameEvent.EventType.FireEmitterChanged;
      emitter_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance();
      oldGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
      newGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
      matchWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      player_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      attackType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType.LEFT_JAB;
      oldHealth_ = 0F;
      newHealth_ = 0F;
      roundNumber_ = 0;
      beginType_ = 0;
      roundWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      timedOut_ = false;
      timeInSecs_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasEmitter()) {
        if (!getEmitter().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, emitter_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, oldGameState_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, newGameState_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, matchWinner_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, player_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, attackType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(9, oldHealth_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(10, newHealth_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(11, roundNumber_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(12, beginType_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeEnum(13, roundWinner_.getNumber());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(14, timedOut_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(15, timeInSecs_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, emitter_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, oldGameState_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, newGameState_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, matchWinner_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, player_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, attackType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, oldHealth_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, newHealth_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, roundNumber_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, beginType_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(13, roundWinner_.getNumber());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, timedOut_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, timeInSecs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.site3.ssf.guiprotocol.Event.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.site3.ssf.guiprotocol.Event.GameEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ca.site3.ssf.guiprotocol.Event.GameEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.site3.ssf.guiprotocol.Event.internal_static_guiprotocol_GameEvent_fieldAccessorTable;
      }
      
      // Construct using ca.site3.ssf.guiprotocol.Event.GameEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEmitterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = ca.site3.ssf.guiprotocol.Event.GameEvent.EventType.FireEmitterChanged;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (emitterBuilder_ == null) {
          emitter_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance();
        } else {
          emitterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        oldGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
        bitField0_ = (bitField0_ & ~0x00000004);
        newGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
        bitField0_ = (bitField0_ & ~0x00000008);
        matchWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        bitField0_ = (bitField0_ & ~0x00000010);
        player_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        bitField0_ = (bitField0_ & ~0x00000020);
        attackType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType.LEFT_JAB;
        bitField0_ = (bitField0_ & ~0x00000040);
        oldHealth_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        newHealth_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        roundNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        beginType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        roundWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        bitField0_ = (bitField0_ & ~0x00000800);
        timedOut_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        timeInSecs_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDescriptor();
      }
      
      public ca.site3.ssf.guiprotocol.Event.GameEvent getDefaultInstanceForType() {
        return ca.site3.ssf.guiprotocol.Event.GameEvent.getDefaultInstance();
      }
      
      public ca.site3.ssf.guiprotocol.Event.GameEvent build() {
        ca.site3.ssf.guiprotocol.Event.GameEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ca.site3.ssf.guiprotocol.Event.GameEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ca.site3.ssf.guiprotocol.Event.GameEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ca.site3.ssf.guiprotocol.Event.GameEvent buildPartial() {
        ca.site3.ssf.guiprotocol.Event.GameEvent result = new ca.site3.ssf.guiprotocol.Event.GameEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (emitterBuilder_ == null) {
          result.emitter_ = emitter_;
        } else {
          result.emitter_ = emitterBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.oldGameState_ = oldGameState_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newGameState_ = newGameState_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.matchWinner_ = matchWinner_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.player_ = player_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.attackType_ = attackType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.oldHealth_ = oldHealth_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.newHealth_ = newHealth_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.roundNumber_ = roundNumber_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.beginType_ = beginType_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.roundWinner_ = roundWinner_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.timedOut_ = timedOut_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.timeInSecs_ = timeInSecs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.site3.ssf.guiprotocol.Event.GameEvent) {
          return mergeFrom((ca.site3.ssf.guiprotocol.Event.GameEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.site3.ssf.guiprotocol.Event.GameEvent other) {
        if (other == ca.site3.ssf.guiprotocol.Event.GameEvent.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasEmitter()) {
          mergeEmitter(other.getEmitter());
        }
        if (other.hasOldGameState()) {
          setOldGameState(other.getOldGameState());
        }
        if (other.hasNewGameState()) {
          setNewGameState(other.getNewGameState());
        }
        if (other.hasMatchWinner()) {
          setMatchWinner(other.getMatchWinner());
        }
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        if (other.hasAttackType()) {
          setAttackType(other.getAttackType());
        }
        if (other.hasOldHealth()) {
          setOldHealth(other.getOldHealth());
        }
        if (other.hasNewHealth()) {
          setNewHealth(other.getNewHealth());
        }
        if (other.hasRoundNumber()) {
          setRoundNumber(other.getRoundNumber());
        }
        if (other.hasBeginType()) {
          setBeginType(other.getBeginType());
        }
        if (other.hasRoundWinner()) {
          setRoundWinner(other.getRoundWinner());
        }
        if (other.hasTimedOut()) {
          setTimedOut(other.getTimedOut());
        }
        if (other.hasTimeInSecs()) {
          setTimeInSecs(other.getTimeInSecs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasEmitter()) {
          if (!getEmitter().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.EventType value = ca.site3.ssf.guiprotocol.Event.GameEvent.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder subBuilder = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.newBuilder();
              if (hasEmitter()) {
                subBuilder.mergeFrom(getEmitter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEmitter(subBuilder.buildPartial());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.GameState value = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                oldGameState_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.GameState value = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                newGameState_ = value;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.Player value = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                matchWinner_ = value;
              }
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.Player value = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                player_ = value;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType value = ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                attackType_ = value;
              }
              break;
            }
            case 77: {
              bitField0_ |= 0x00000080;
              oldHealth_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000100;
              newHealth_ = input.readFloat();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000200;
              roundNumber_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000400;
              beginType_ = input.readInt32();
              break;
            }
            case 104: {
              int rawValue = input.readEnum();
              ca.site3.ssf.guiprotocol.Event.GameEvent.Player value = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(13, rawValue);
              } else {
                bitField0_ |= 0x00000800;
                roundWinner_ = value;
              }
              break;
            }
            case 112: {
              bitField0_ |= 0x00001000;
              timedOut_ = input.readBool();
              break;
            }
            case 120: {
              bitField0_ |= 0x00002000;
              timeInSecs_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .guiprotocol.GameEvent.EventType type = 1;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.EventType type_ = ca.site3.ssf.guiprotocol.Event.GameEvent.EventType.FireEmitterChanged;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.EventType getType() {
        return type_;
      }
      public Builder setType(ca.site3.ssf.guiprotocol.Event.GameEvent.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ca.site3.ssf.guiprotocol.Event.GameEvent.EventType.FireEmitterChanged;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.FireEmitter emitter = 2;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter emitter_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder> emitterBuilder_;
      public boolean hasEmitter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter getEmitter() {
        if (emitterBuilder_ == null) {
          return emitter_;
        } else {
          return emitterBuilder_.getMessage();
        }
      }
      public Builder setEmitter(ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter value) {
        if (emitterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          emitter_ = value;
          onChanged();
        } else {
          emitterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setEmitter(
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder builderForValue) {
        if (emitterBuilder_ == null) {
          emitter_ = builderForValue.build();
          onChanged();
        } else {
          emitterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeEmitter(ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter value) {
        if (emitterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              emitter_ != ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance()) {
            emitter_ =
              ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.newBuilder(emitter_).mergeFrom(value).buildPartial();
          } else {
            emitter_ = value;
          }
          onChanged();
        } else {
          emitterBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearEmitter() {
        if (emitterBuilder_ == null) {
          emitter_ = ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.getDefaultInstance();
          onChanged();
        } else {
          emitterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder getEmitterBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEmitterFieldBuilder().getBuilder();
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder getEmitterOrBuilder() {
        if (emitterBuilder_ != null) {
          return emitterBuilder_.getMessageOrBuilder();
        } else {
          return emitter_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder> 
          getEmitterFieldBuilder() {
        if (emitterBuilder_ == null) {
          emitterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder, ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitterOrBuilder>(
                  emitter_,
                  getParentForChildren(),
                  isClean());
          emitter_ = null;
        }
        return emitterBuilder_;
      }
      
      // optional .guiprotocol.GameEvent.GameState oldGameState = 3;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.GameState oldGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
      public boolean hasOldGameState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getOldGameState() {
        return oldGameState_;
      }
      public Builder setOldGameState(ca.site3.ssf.guiprotocol.Event.GameEvent.GameState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        oldGameState_ = value;
        onChanged();
        return this;
      }
      public Builder clearOldGameState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        oldGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.GameState newGameState = 4;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.GameState newGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
      public boolean hasNewGameState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.GameState getNewGameState() {
        return newGameState_;
      }
      public Builder setNewGameState(ca.site3.ssf.guiprotocol.Event.GameEvent.GameState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        newGameState_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewGameState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newGameState_ = ca.site3.ssf.guiprotocol.Event.GameEvent.GameState.NO_STATE;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.Player matchWinner = 5;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.Player matchWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      public boolean hasMatchWinner() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getMatchWinner() {
        return matchWinner_;
      }
      public Builder setMatchWinner(ca.site3.ssf.guiprotocol.Event.GameEvent.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        matchWinner_ = value;
        onChanged();
        return this;
      }
      public Builder clearMatchWinner() {
        bitField0_ = (bitField0_ & ~0x00000010);
        matchWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.Player player = 6;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.Player player_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getPlayer() {
        return player_;
      }
      public Builder setPlayer(ca.site3.ssf.guiprotocol.Event.GameEvent.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        player_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000020);
        player_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.AttackType attackType = 7;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType attackType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType.LEFT_JAB;
      public boolean hasAttackType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType getAttackType() {
        return attackType_;
      }
      public Builder setAttackType(ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        attackType_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttackType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        attackType_ = ca.site3.ssf.guiprotocol.Event.GameEvent.AttackType.LEFT_JAB;
        onChanged();
        return this;
      }
      
      // optional float oldHealth = 9;
      private float oldHealth_ ;
      public boolean hasOldHealth() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public float getOldHealth() {
        return oldHealth_;
      }
      public Builder setOldHealth(float value) {
        bitField0_ |= 0x00000080;
        oldHealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearOldHealth() {
        bitField0_ = (bitField0_ & ~0x00000080);
        oldHealth_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float newHealth = 10;
      private float newHealth_ ;
      public boolean hasNewHealth() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public float getNewHealth() {
        return newHealth_;
      }
      public Builder setNewHealth(float value) {
        bitField0_ |= 0x00000100;
        newHealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewHealth() {
        bitField0_ = (bitField0_ & ~0x00000100);
        newHealth_ = 0F;
        onChanged();
        return this;
      }
      
      // optional int32 roundNumber = 11;
      private int roundNumber_ ;
      public boolean hasRoundNumber() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getRoundNumber() {
        return roundNumber_;
      }
      public Builder setRoundNumber(int value) {
        bitField0_ |= 0x00000200;
        roundNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoundNumber() {
        bitField0_ = (bitField0_ & ~0x00000200);
        roundNumber_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 beginType = 12;
      private int beginType_ ;
      public boolean hasBeginType() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getBeginType() {
        return beginType_;
      }
      public Builder setBeginType(int value) {
        bitField0_ |= 0x00000400;
        beginType_ = value;
        onChanged();
        return this;
      }
      public Builder clearBeginType() {
        bitField0_ = (bitField0_ & ~0x00000400);
        beginType_ = 0;
        onChanged();
        return this;
      }
      
      // optional .guiprotocol.GameEvent.Player roundWinner = 13;
      private ca.site3.ssf.guiprotocol.Event.GameEvent.Player roundWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
      public boolean hasRoundWinner() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public ca.site3.ssf.guiprotocol.Event.GameEvent.Player getRoundWinner() {
        return roundWinner_;
      }
      public Builder setRoundWinner(ca.site3.ssf.guiprotocol.Event.GameEvent.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000800;
        roundWinner_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoundWinner() {
        bitField0_ = (bitField0_ & ~0x00000800);
        roundWinner_ = ca.site3.ssf.guiprotocol.Event.GameEvent.Player.RINGMASTER;
        onChanged();
        return this;
      }
      
      // optional bool timedOut = 14;
      private boolean timedOut_ ;
      public boolean hasTimedOut() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public boolean getTimedOut() {
        return timedOut_;
      }
      public Builder setTimedOut(boolean value) {
        bitField0_ |= 0x00001000;
        timedOut_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimedOut() {
        bitField0_ = (bitField0_ & ~0x00001000);
        timedOut_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 timeInSecs = 15;
      private int timeInSecs_ ;
      public boolean hasTimeInSecs() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getTimeInSecs() {
        return timeInSecs_;
      }
      public Builder setTimeInSecs(int value) {
        bitField0_ |= 0x00002000;
        timeInSecs_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeInSecs() {
        bitField0_ = (bitField0_ & ~0x00002000);
        timeInSecs_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:guiprotocol.GameEvent)
    }
    
    static {
      defaultInstance = new GameEvent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:guiprotocol.GameEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guiprotocol_GameEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guiprotocol_GameEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guiprotocol_GameEvent_FireEmitter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guiprotocol_GameEvent_FireEmitter_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\013guiprotocol\"\271\013\n\tGameEvent" +
      "\022.\n\004type\030\001 \002(\0162 .guiprotocol.GameEvent.E" +
      "ventType\0223\n\007emitter\030\002 \001(\0132\".guiprotocol." +
      "GameEvent.FireEmitter\0226\n\014oldGameState\030\003 " +
      "\001(\0162 .guiprotocol.GameEvent.GameState\0226\n" +
      "\014newGameState\030\004 \001(\0162 .guiprotocol.GameEv" +
      "ent.GameState\0222\n\013matchWinner\030\005 \001(\0162\035.gui" +
      "protocol.GameEvent.Player\022-\n\006player\030\006 \001(" +
      "\0162\035.guiprotocol.GameEvent.Player\0225\n\natta" +
      "ckType\030\007 \001(\0162!.guiprotocol.GameEvent.Att",
      "ackType\022\021\n\toldHealth\030\t \001(\002\022\021\n\tnewHealth\030" +
      "\n \001(\002\022\023\n\013roundNumber\030\013 \001(\005\022\021\n\tbeginType\030" +
      "\014 \001(\005\0222\n\013roundWinner\030\r \001(\0162\035.guiprotocol" +
      ".GameEvent.Player\022\020\n\010timedOut\030\016 \001(\010\022\022\n\nt" +
      "imeInSecs\030\017 \001(\005\032\261\001\n\013FireEmitter\022\024\n\014emitt" +
      "erIndex\030\001 \002(\005\022;\n\013emitterType\030\002 \002(\0162&.gui" +
      "protocol.GameEvent.FireEmitterType\022\033\n\023in" +
      "tensityRingmaster\030\003 \002(\002\022\030\n\020intensityPlay" +
      "er1\030\004 \002(\002\022\030\n\020intensityPlayer2\030\005 \002(\002\"\356\001\n\t" +
      "EventType\022\026\n\022FireEmitterChanged\020\000\022\024\n\020Gam",
      "eStateChanged\020\001\022\027\n\023PlayerHealthChanged\020\002" +
      "\022\031\n\025RoundPlayTimerChanged\020\003\022\032\n\026RoundBegi" +
      "nTimerChanged\020\004\022\016\n\nRoundEnded\020\005\022\016\n\nMatch" +
      "Ended\020\006\022\026\n\022PlayerAttackAction\020\007\022\025\n\021Playe" +
      "rBlockAction\020\010\022\024\n\020RingmasterAction\020\t\"\320\001\n" +
      "\tGameState\022\014\n\010NO_STATE\020\000\022\031\n\025ROUND_BEGINN" +
      "ING_STATE\020\001\022\027\n\023ROUND_IN_PLAY_STATE\020\002\022\025\n\021" +
      "ROUND_ENDED_STATE\020\003\022\033\n\027TIE_BREAKER_ROUND" +
      "_STATE\020\004\022\025\n\021MATCH_ENDED_STATE\020\005\022\020\n\014PAUSE" +
      "D_STATE\020\006\022\024\n\020RINGMASTER_STATE\020\007\022\016\n\nIDLE_",
      "STATE\020\010\"(\n\006Player\022\016\n\nRINGMASTER\020\000\022\006\n\002P1\020" +
      "\001\022\006\n\002P2\020\002\"@\n\017FireEmitterType\022\r\n\tLEFT_RAI" +
      "L\020\000\022\016\n\nRIGHT_RAIL\020\001\022\016\n\nOUTER_RING\020\002\"I\n\020F" +
      "lameEmitterType\022\020\n\014ATTACK_FLAME\020\000\022\017\n\013BLO" +
      "CK_FLAME\020\001\022\022\n\016NON_GAME_FLAME\020\002\"f\n\nAttack" +
      "Type\022\014\n\010LEFT_JAB\020\000\022\r\n\tRIGHT_JAB\020\001\022\r\n\tLEF" +
      "T_HOOK\020\002\022\016\n\nRIGHT_HOOK\020\003\022\014\n\010HADOUKEN\020\004\022\016" +
      "\n\nSONIC_BOOM\020\005B\032\n\030ca.site3.ssf.guiprotoc" +
      "ol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_guiprotocol_GameEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_guiprotocol_GameEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guiprotocol_GameEvent_descriptor,
              new java.lang.String[] { "Type", "Emitter", "OldGameState", "NewGameState", "MatchWinner", "Player", "AttackType", "OldHealth", "NewHealth", "RoundNumber", "BeginType", "RoundWinner", "TimedOut", "TimeInSecs", },
              ca.site3.ssf.guiprotocol.Event.GameEvent.class,
              ca.site3.ssf.guiprotocol.Event.GameEvent.Builder.class);
          internal_static_guiprotocol_GameEvent_FireEmitter_descriptor =
            internal_static_guiprotocol_GameEvent_descriptor.getNestedTypes().get(0);
          internal_static_guiprotocol_GameEvent_FireEmitter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guiprotocol_GameEvent_FireEmitter_descriptor,
              new java.lang.String[] { "EmitterIndex", "EmitterType", "IntensityRingmaster", "IntensityPlayer1", "IntensityPlayer2", },
              ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.class,
              ca.site3.ssf.guiprotocol.Event.GameEvent.FireEmitter.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
